namespace Dynamicweb.DataIntegration.Providers.ODataProvider.Model
{
    internal class OrderLines
    {
        public string Document_Type { get; set; }
        public string Document_No { get; set; }
        public int Line_No { get; set; }
        public string Type { get; set; }
        public string FilteredTypeField { get; set; }
        public string No { get; set; }
        public string Cross_Reference_No { get; set; }
        public string IC_Partner_Code { get; set; }
        public string IC_Partner_Ref_Type { get; set; }
        public string IC_Partner_Reference { get; set; }
        public string Variant_Code { get; set; }
        public string Purchasing_Code { get; set; }
        public bool Nonstock { get; set; }
        public string VAT_Prod_Posting_Group { get; set; }
        public string Description { get; set; }
        public bool Drop_Shipment { get; set; }
        public bool Special_Order { get; set; }
        public string Return_Reason_Code { get; set; }
        public string Location_Code { get; set; }
        public string Bin_Code { get; set; }
        public string Control50 { get; set; }
        public int Quantity { get; set; }
        public int Qty_to_Assemble_to_Order { get; set; }
        public int Reserved_Quantity { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public string Unit_of_Measure { get; set; }
        public double Unit_Cost_LCY { get; set; }
        public bool SalesPriceExist { get; set; }
        public double Unit_Price { get; set; }
        public bool Tax_Liable { get; set; }
        public string Tax_Area_Code { get; set; }
        public string Tax_Group_Code { get; set; }
        public double Line_Discount_Percent { get; set; }
        public double Line_Amount { get; set; }
        public bool SalesLineDiscExists { get; set; }
        public double Line_Discount_Amount { get; set; }
        public double Prepayment_Percent { get; set; }
        public double Prepmt_Line_Amount { get; set; }
        public int Prepmt_Amt_Inv { get; set; }
        public bool Allow_Invoice_Disc { get; set; }
        public double Inv_Discount_Amount { get; set; }
        public double Inv_Disc_Amount_to_Invoice { get; set; }
        public int Qty_to_Ship { get; set; }
        public int Quantity_Shipped { get; set; }
        public int Qty_to_Invoice { get; set; }
        public int Quantity_Invoiced { get; set; }
        public int Prepmt_Amt_to_Deduct { get; set; }
        public int Prepmt_Amt_Deducted { get; set; }
        public bool Allow_Item_Charge_Assignment { get; set; }
        public int Qty_to_Assign { get; set; }
        public int Qty_Assigned { get; set; }
        public string Requested_Delivery_Date { get; set; }
        public string Promised_Delivery_Date { get; set; }
        public string Planned_Delivery_Date { get; set; }
        public string Planned_Shipment_Date { get; set; }
        public string Shipment_Date { get; set; }
        public string Shipping_Agent_Code { get; set; }
        public string Shipping_Agent_Service_Code { get; set; }
        public string Shipping_Time { get; set; }
        public string Work_Type_Code { get; set; }
        public int Whse_Outstanding_Qty { get; set; }
        public int Whse_Outstanding_Qty_Base { get; set; }
        public int ATO_Whse_Outstanding_Qty { get; set; }
        public int ATO_Whse_Outstd_Qty_Base { get; set; }
        public string Outbound_Whse_Handling_Time { get; set; }
        public string Blanket_Order_No { get; set; }
        public int Blanket_Order_Line_No { get; set; }
        public string FA_Posting_Date { get; set; }
        public bool Depr_until_FA_Posting_Date { get; set; }
        public string Depreciation_Book_Code { get; set; }
        public bool Use_Duplication_List { get; set; }
        public string Duplicate_in_Depreciation_Book { get; set; }
        public int Appl_from_Item_Entry { get; set; }
        public int Appl_to_Item_Entry { get; set; }
        public string Deferral_Code { get; set; }
        public string Shortcut_Dimension_1_Code { get; set; }
        public string Shortcut_Dimension_2_Code { get; set; }
        public string ShortcutDimCode3 { get; set; }
        public string ShortcutDimCode4 { get; set; }
        public string ShortcutDimCode5 { get; set; }
        public string ShortcutDimCode6 { get; set; }
        public string ShortcutDimCode7 { get; set; }
        public string ShortcutDimCode8 { get; set; }
        public double TotalSalesLine_Line_Amount { get; set; }
        public double Invoice_Discount_Amount { get; set; }
        public double Invoice_Disc_Pct { get; set; }
        public double Total_Amount_Excl_VAT { get; set; }
        public double Total_VAT_Amount { get; set; }
        public double Total_Amount_Incl_VAT { get; set; }
    }
}
